# Generated by Django 5.1.6 on 2025-02-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ships", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ship",
            options={"verbose_name": "СУДА", "verbose_name_plural": "Судно"},
        ),
    ]
