# Generated by Django 5.1.6 on 2025-02-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0003_alter_ship_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ship',
            options={'verbose_name': 'Судно', 'verbose_name_plural': 'Судно'},
        ),
    ]
