# Generated by Django 5.1.6 on 2025-02-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0005_alter_ship_options_alter_ship_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ship',
            options={'verbose_name': 'Судно', 'verbose_name_plural': 'Судно/теплоход'},
        ),
        migrations.AlterField(
            model_name='ship',
            name='capacity',
            field=models.IntegerField(verbose_name='Вместимость, пасс.'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название судна'),
        ),
    ]
