# Generated by Django 5.1.6 on 2025-02-15 05:32

import passenger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passenger", "0003_passenger_first_name_passenger_last_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passenger",
            options={"verbose_name": "Пассажир", "verbose_name_plural": "Пассажиры"},
        ),
        migrations.RemoveField(
            model_name="passenger",
            name="passport",
        ),
        migrations.AddField(
            model_name="passenger",
            name="passport_number",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[passenger.models.validate_passport_number],
                verbose_name="Номер паспорта",
            ),
        ),
        migrations.AddField(
            model_name="passenger",
            name="passport_series",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                validators=[passenger.models.validate_passport_series],
                verbose_name="Серия паспорта",
            ),
        ),
    ]
