# Generated by Django 5.1.6 on 2025-02-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_route_options_alter_stop_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routepoint',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время отправления'),
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='price_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Множитель цены'),
        ),
    ]
