# Generated by Django 5.1.6 on 2025-02-14 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_routepoint_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routepoint',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок'),
        ),
    ]
