# Generated by Django 5.1.6 on 2025-02-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_alter_route_arrival_location_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routepoint',
            unique_together={('route', 'order')},
        ),
    ]
