# Generated by Django 5.1.6 on 2025-02-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_stop_created_at_stop_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stop',
            options={'verbose_name': 'Остановочный пункт', 'verbose_name_plural': 'Остановочные пункты'},
        ),
    ]
