# Generated by Django 5.1.6 on 2025-02-14 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voyages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voyage",
            name="available_seats",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Доступные места",
            ),
        ),
    ]
