# Generated by Django 5.1.6 on 2025-02-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0003_remove_voyage_arrival_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voyagestopprice',
            options={'verbose_name': 'Стоимость билета до остановки', 'verbose_name_plural': 'Стоимости билета до остановки'},
        ),
    ]
