# Generated by Django 5.1.6 on 2025-02-16 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0009_alter_stop_options"),
        ("voyages", "0004_alter_voyagestopprice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="voyage",
            name="departure_date",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="routes.routedeparturedate",
                verbose_name="Дата отправления",
            ),
        ),
    ]
