# Generated by Django 5.1.6 on 2025-02-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voyages", "0005_voyage_departure_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voyage",
            name="departure_date",
        ),
    ]
