# Generated by Django 5.1.6 on 2025-02-15 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passenger', '0002_alter_passenger_options'),
        ('voyages', '0002_alter_voyage_available_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID билета')),
                ('seat_number', models.IntegerField(verbose_name='Номер места')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('qr_code', models.CharField(max_length=255, verbose_name='QR-код')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passenger.passenger', verbose_name='Пассажир')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyages.voyage', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
