# Generated by Django 5.1.6 on 2025-02-16 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "passenger",
            "0005_alter_passenger_first_name_alter_passenger_last_name_and_more",
        ),
        ("routes", "0009_alter_stop_options"),
        ("voyages", "0006_remove_voyage_departure_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "ticket_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID билета"
                    ),
                ),
                (
                    "seat_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Номер места"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата оформления"
                    ),
                ),
                ("status", models.CharField(max_length=50, verbose_name="Статус")),
                ("is_paid", models.BooleanField(default=False, verbose_name="Оплачен")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "arrival_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrival_tickets",
                        to="routes.stop",
                        verbose_name="Пункт прибытия",
                    ),
                ),
                (
                    "departure_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departure_tickets",
                        to="routes.stop",
                        verbose_name="Пункт отправления",
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="passenger.passenger",
                        verbose_name="Пассажир",
                    ),
                ),
                (
                    "voyage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voyages.voyage",
                        verbose_name="Рейс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Билет",
                "verbose_name_plural": "Билеты",
            },
        ),
    ]
