# Generated by Django 5.1.6 on 2025-02-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_alter_stop_options'),
        ('ticket', '0002_remove_ticket_qr_code_alter_ticket_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='arrival_stop',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_tickets', to='routes.stop', verbose_name='Пункт прибытия'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='departure_stop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departure_tickets', to='routes.stop', verbose_name='Пункт отправления'),
        ),
    ]
