# Generated by Django 5.1.6 on 2025-02-15 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_alter_stop_options'),
        ('ticket', '0003_ticket_arrival_stop_ticket_departure_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='arrival_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_tickets', to='routes.stop', verbose_name='Пункт прибытия'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_tickets', to='routes.stop', verbose_name='Пункт отправления'),
        ),
    ]
